// This file is templated by scitran.py.
// Edits to the generated file will not be saved!

var BASE_URL = 'SCITRAN-BASE-URL';
var VERIFICATION_ENDPOINT  = 'SCITRAN-AUTH-VERIFY-URL';
var AUTHENTICATION_ENDPOINT = 'SCITRAN-AUTH-AUTH-URL';
var AUTHENTICATION_PROVIDER = 'SCITRAN-AUTH-PROVIDER';
var CLIENT_ID = 'SCITRAN-AUTH-CLIENTID';
